import time
import random

global sysadminName

def intro():
    global sysadminName
    print(f"Starting the game...")
    time.sleep(2)
    sysadminName = input("What is your name? ")
    time.sleep(2)
    print(f"Welcome to the game, {sysadminName}")
    time.sleep(1)
    print(f"You are starting off another day at \"Everything is Broken Corp\" where everything is...")
    time.sleep(3)
    wellBroken = "well... broken..."
    wellBroken = wellBroken.split()
    for word in wellBroken:
        print(word)
        time.sleep(3)
    print(f"You will be given a series of decisions to make that can impact your job and others around you.")
    time.sleep(3)
    print("Some decisions will end your game quicker than others. See if you can make it back home without destroying the company!")
    time.sleep(5)
    print()
    game()

def game():
    global sysadminName
    print(f"You wake up")
    time.sleep(5)
    print(f"An incoherent string of text is on your screen and your face is imprinted with the keys from your keyboard")
    time.sleep(5)
    print()
    print(f"\"Time to get back to work and do these tickets in my queue: \"")
    time.sleep(3)
    print(f"    ##################################################################################################################################")
    print(f"    #  1. \"Multiple users report that sometimes when they come back in to the office, they are unable to connect to the internet\"")
    print(f"    #                                                                                     - Eli, Helpdesk Tech")
    print(f"    #")
    print(f"    #  2. \"The coffee machine is broken\"")
    print(f"    #                            - Matt, accountant")
    print(f"    #")
    print(f"    #  3. \"Go home\"")
    print(f"    #")
    print(f"    #  4. You probably shouldn't do this one but... give it a try and see what happens!")
    print(f"    ##################################################################################################################################")
    print(f"")
    
    firstChoice = input(f"Select a choice: ")
    print("")
    print("")

    if firstChoice == "1":
        firstChoice1()
    elif firstChoice == "2":
        firstChoice2()
    elif firstChoice == "3":
        firstChoice3()
    elif firstChoice == "4":
        print(f"You navigate to the root directory of each hypervisor and you try this cool trick that you read on reddit from the subreddit r/linuxmemes")
        time.sleep(8)
        print(f"rm -rf")
        time.sleep(3)
        print(f"The screen turns black. \"Everything is Broken Corp\" is now \"Everything is On Fire Corp\".")
        time.sleep(2)
        print(f"Rewinding this sequence... Try again in: ")
        time.sleep(2)
        print(f"3")
        time.sleep(2)
        print(f"2")
        time.sleep(2)
        print(f"1")
        time.sleep(3)
        game()
    else:
        print(f"Invalid choice. Please choose a number between 1 and 4.")
        game()

########################################################################################################################
#CHOICE 1 SEQUENCE
########################################################################################################################
def firstChoice1():
    print(f"You remote in to the Domain Controller that has a DHCP role.")
    print(f"What will you do?")
    time.sleep(6)
    print(f"    ##################################################################################################################################")
    print(f"    #  1. Check the logs")
    print(f"    #")
    print(f"    #  2. Delete the logs")
    print(f"    #")
    print(f"    ##################################################################################################################################")
    print(f"")

    firstChoice1Input = input(f"Select a choice: ")

    if firstChoice1Input == "1":
        print(f"Woah! Slow down buddy. You're not doing actual work are you??? Did you forget the name of the game??? Let me remind you: ")
        time.sleep(2)
        print("")
        print("")
        time.sleep(2)
        print(f"    #########################################")
        time.sleep(2)
        print(f"    Welcome to Terrible Sysadmin Simulator!")
        time.sleep(2)
        print(f"    #########################################")
        time.sleep(2)
        print()
        print()
        print(f"Let's rewind this in: ")
        time.sleep(2)
        print(f"3")
        time.sleep(2)
        print(f"2")
        time.sleep(2)
        print(f"1")
        time.sleep(3)
        firstChoice1()
    elif firstChoice1Input == "2":
        print("You delete the logs then log out of the server")
        time.sleep(3)
        print("You close the ticket and leave the office after a hard minute's work")
        time.sleep(5)
        print(f"You go home and take a nap")
        time.sleep(5)
        print(f"You wake up to a voicemail from your Director telling you that you are fired")
        time.sleep(3)
        print(f"....")
        time.sleep(3)
        print(f"....")
        time.sleep(5)
        print(f"Congrats you win!")
        pregame()
    else:
        print("Select 1 or 2")
        firstChoice1()



########################################################################################################################
#CHOICE 2 SEQUENCE
########################################################################################################################
def firstChoice2():
    print("You go to check out the coffee machine. What should you do?")
    time.sleep(3)

    print(f"    ##################################################################################################################################")
    print(f"    #  1. Go back to your desk and close the ticket with no response")
    print(f"    #")
    print(f"    #  2. Investigate the coffee machine more")
    print(f"    #")
    print(f"    #  3. Drink the coffee")
    print(f"    #                           ")  
    print(f"    #  4. Pour the coffee on to some equipment")
    print(f"    #                            ")
    print(f"    ##################################################################################################################################")
    print(f"")

    firstChoice2Input = input(f"Select a choice: ")

    if firstChoice2Input == "1":
        firstChoice2_1()
    elif firstChoice2Input == "2":
        firstChoice2_2()
    elif firstChoice2Input == "3":
        firstChoice2_3()
    elif firstChoice2Input == "4":
        firstChoice2_4()
    else:
        randomNumber = random.randint(1,4)
        print(f"Invalid input. We thought about looping you back to this prompt again and requesting that you only choose a valid number. However, I thought that now would be a good time to try the \"random\" method. A random VALID number will now be chosen for you.")
        time.sleep(8)
        print("The number our random generator chose is!!!!!!")
        print("*Drum roll*")
        time.sleep(5)
        print(f"{randomNumber}!!! Congrats!")
        print(f"Executing your (but not really \"yours\") new choice now!!")
        time.sleep(5)
        if randomNumber == 1:
            firstChoice2_1()
        elif randomNumber == 2:
            firstChoice2_2()
        elif randomNumber == 3:
            firstChoice2_3()
        else:
            firstChoice2_4()
    
def firstChoice2_4():
    print(f"\"The firewalls have been consistently reporting high temps,\" you think to yourself.")
    time.sleep(3)
    print(f"You go in to the network closet and find your two firewalls. As usual they feel pretty heated.. at least more so than normal.")
    time.sleep(3)
    print(f"You pour the coffee on to the appliances. Sparks fly and the network closet gets a little quieter.")
    time.sleep(3)
    print(f"The firewall cools down.")
    time.sleep(3)
    print(f"You walk out and head to your car, deciding to get something to eat and head home.")
    time.sleep(7)
    print(f"You pass a Whataburger and a McDonald's.")
    print(f"")
    print(f"    ##################################################################################################################################")
    print(f"    #  1. Whataburger")
    print(f"    #")
    print(f"    #  2. McDonald's")
    print(f"    #")
    print(f"    ##################################################################################################################################")
    print(f"")
    firstChoice2_4_input = input(f"What are we eating? ")
    if firstChoice2_4_input == "1":
        print(f"")
        time.sleep(2)
        print(f"You go to the drive thru and order a feast: A 3 chicken strip meal, a honey barbecue chicken strip sandwich on Texas Toast meal, Large onion rings, a large milkshake, a large sweet tea, and a triple bacon whataburger meal")
        print(f"")
        time.sleep(3)
        print(f"You get home quickly (Of course within the speed limit!!!) and you dig in to the feast!")
        time.sleep(3)
        print(f"You pass out in a food coma.")
        time.sleep(3)
        print(f"Your phone buzzes and buzzes and buzzes but you toss it across the room and go back to sleep")
        time.sleep(3)
        print(f"SURPRISE!!!!!!!")
        time.sleep(1)
        print(f"The Police come in and arrest you!")
        time.sleep(1)
        time.sleep(1)
        print(f"Rewinding the sequence in: ")
        time.sleep(1)
        print(f"3")
        time.sleep(2)
        print(f"2")
        time.sleep(2)
        print(f"1")
        time.sleep(2)
        game()
    elif firstChoice2_4_input == "2":
        print(f"")
        time.sleep(2)
        print(f"You go to the drive thru and order a feast: A 20 piece spicy nugget meal, two McRibs, 3 McDoubles, a large mango smoothie, a big mac, and a large sweet tea, and a quarter pounder")
        print(f"")
        time.sleep(3)
        print(f"You get home quickly (Of course within the speed limit!!!) and you dig in to the feast!")
        time.sleep(3)
        print(f"You pass out in a food coma.")
        time.sleep(3)
        print(f"Your phone buzzes and buzzes and buzzes but you toss it across the room and go back to sleep")
        time.sleep(3)
        print(f"SURPRISE!!!!!!!")
        time.sleep(1)
        print(f"The Police come in and arrest you!")
        time.sleep(1)
        time.sleep(1)
        print(f"Rewinding the sequence in: ")
        time.sleep(1)
        print(f"3")
        time.sleep(2)
        print(f"2")
        time.sleep(2)
        print(f"1")
        time.sleep(2)
        game()
    else:
        print(f"Please choose 1 or 2. Rewinding sequence in: ")
        time.sleep(1)
        print(f"3")
        time.sleep(2)
        print(f"2")
        time.sleep(2)
        print(f"1")
        time.sleep(2)
        firstChoice2_4()

def firstChoice2_2():
    print(f"You choose to investigate the coffee machine more.")
    time.sleep(3)
    print(f"You notice the machine begins to heat up more.")
    time.sleep(5)
    print(f"You click the off switch")
    time.sleep(5)
    print(f"It seems that it does not work. The machine continues to heat up")
    time.sleep(5)
    print(f"You now unplug the machine!")
    time.sleep(5)
    print(f"Nothing happens! The pot begins to turn red and the coffee is violently boiling.")
    time.sleep(5)
    print(f"A burning smell permeates the room")
    time.sleep(5)
    print(f"The machine explodes and the room is on fire")
    time.sleep(5)
    print(f"You get everyone out of the building")
    time.sleep(5)
    print(f"Eventually the Fire department and Police arrive.")
    time.sleep(5)
    print(f"You approach them to speak to them and next thing you know you're on the ground getting put in to cuffs")
    time.sleep(5)
    print(f"It appears you have been accused and all of those years of weaponized incompetence has caught up with you. No one believes your absolutely ridiculous story.")
    time.sleep(10)
    print(f"Really... Who is going to believe some clown that tells you \"the coffee machine kept heating up after I unplugged it.\" What is this, Tom and Jerry?")
    time.sleep(10)
    print(f"Rewinding sequence in: ")
    time.sleep(1)
    print(f"3")
    time.sleep(2)
    print(f"2")
    time.sleep(2)
    print(f"1")
    time.sleep(2)
    game()

def firstChoice2_3():
    print(f"You grab the pot and notice that it is still hot, despite being broken???")
    time.sleep(4)
    print(f"You drink the coffee straight from the pot.")
    time.sleep(4)
    print(f"You burn your mouth and throat")
    time.sleep(4)
    print(f"You end up in the ER.")
    time.sleep(4)
    print(f"Looks like you aren't going home anytime soon, genius")
    time.sleep(4)
    print(f"Rewinding sequence in: ")
    time.sleep(1)
    print(f"3")
    time.sleep(2)
    print(f"2")
    time.sleep(2)
    print(f"1")
    time.sleep(2)
    firstChoice2()

def firstChoice2_1():
    print(f"You shrug your shoulders")
    time.sleep(2)
    print(f"\"Not my problem. I'm closing this ticket. Knowing Accounting, they will probably reopen it though....\"")
    time.sleep(2)
    print(f"....")
    time.sleep(2)
    print(f"....")
    time.sleep(2)
    print(f"You doze off....")
    time.sleep(10)
    game()

########################################################################################################################
#CHOICE 3 SEQUENCE
########################################################################################################################

def firstChoice3():
    global sysadminName
    print(f"You get up and collect your things and book it towards the exit of the building")
    time.sleep(3)
    print("")
    print(f"All of the people whom you have tickets for try to talk to you as you pick up the pace")
    time.sleep(3)
    print("")
    print("You make it out the building and start power-walking down the street and abruptly stop....")
    time.sleep(2)
    print("")
    print("???????????????????????????????")
    time.sleep(3)
    print("")
    print(f"\"Wait a minute... I own a car\", you think to yourself. You begin walking back and get in the car")
    time.sleep(4)
    print(f"You try to start it but it doesn't work. Then you hear a knock. It's your manager!!!")
    time.sleep(4)
    print(f"")
    print(f"    ##################################################################################################################################")
    print(f"    #  1. Stay very still. They can't see you if you don't move")
    print(f"    #")
    print(f"    #  2. Run")
    print(f"    #")
    print(f"    #  3. Accept your fate and talk to him")
    print(f"    #")
    print(f"    ##################################################################################################################################")
    print(f"")

    firstChoice3Input = input(f"what do you do? ")

    if firstChoice3Input == "1":
        firstChoice3_1()
    elif firstChoice3Input == "2":
        firstChoice3_2()
    elif firstChoice3Input == "3":
        firstChoice3_3()
    else:
        print("The car explodes. The end.")
        time.sleep(2)
        print("Nice try. We thought that you would try to be a rebel. Choose 1 through 3 please. Try again in:  ")
        time.sleep(3)
        print("3")
        time.sleep(3)
        print("2")
        time.sleep(3)
        print("1")
        time.sleep(3)
        firstChoice3()

def firstChoice3_2():
    global sysadminName
    print(f"You swing the door open and sprint like an Olympian off in to the distance")
    time.sleep(5)
    print("")
    print(f"You finally slow down as the building disappears out of sight")
    print(f"")
    time.sleep(5)
    print(".....")
    print("")
    time.sleep(5)
    print(f"You snap back to reality in your car with your manager standing outside.")
    time.sleep(3)
    print("What? You didn't think we were actually running, did you? There is a heat wave!")
    time.sleep(5)
    print("Try again in: ")
    time.sleep(2)
    print(f"3")
    time.sleep(2)
    print(f"2")
    time.sleep(2)
    print(f"1")
    firstChoice3()


def firstChoice3_1():
    global sysadminName
    print(f"You freeze and remain in a statue like state for several minutes.")
    time.sleep(3)
    print(f"He calls to you, \"{sysadminName}! Hellooooo\". He eventually gives up and goes inside")
    time.sleep(3)
    print(f"Your car finally starts and you go on your merry way.")
    time.sleep(5)
    print("You pass a Whataburger and a McDonald's.")
    print(f"")
    print(f"    ##################################################################################################################################")
    print(f"    #  1. Whataburger")
    print(f"    #")
    print(f"    #  2. McDonald's")
    print(f"    #")
    print(f"    ##################################################################################################################################")
    print(f"")
    firstChoice3_1_input = input(f"What are we eating? ")
    if firstChoice3_1_input == "1":
        print(f"")
        time.sleep(2)
        print(f"You go to the drive thru and order a feast: A 3 chicken strip meal, a honey barbecue chicken strip sandwich on Texas Toast meal, Large onion rings, a large milkshake, a large sweet tea, and a triple bacon whataburger meal")
        print(f"")
        time.sleep(3)
        print(f"You get home quickly (Of course within the speed limit!!!) and you dig in to the feast!")
        time.sleep(3)
        print(f"You pass out in a food coma.")
        time.sleep(3)
        print(f"Your phone buzzes and buzzes and buzzes but you toss it across the room and go back to sleep")
        time.sleep(3)
        print(f"SURPRISE!!!!!!!")
        time.sleep(1)
        print(f"Congrats you won the game! Did you expect that this would be the correct ending?")
        time.sleep(1)
        print(f"Thank you for playing")
        time.sleep(1)
        print(f"Returning to the start sequence in: ")
        time.sleep(1)
        print(f"3")
        time.sleep(2)
        print(f"2")
        time.sleep(2)
        print(f"1")
        time.sleep(2)
        pregame()
    elif firstChoice3_1_input == "2":
        print(f"")
        time.sleep(2)
        print(f"You go to the drive thru and order a feast: A 20 piece spicy nugget meal, two McRibs, 3 McDoubles, a large mango smoothie, a big mac, and a large sweet tea, and a quarter pounder")
        print(f"")
        time.sleep(3)
        print(f"You get home quickly (Of course within the speed limit!!!) and you dig in to the feast!")
        time.sleep(3)
        print(f"You pass out in a food coma.")
        time.sleep(3)
        print(f"Your phone buzzes and buzzes and buzzes but you toss it across the room and go back to sleep")
        time.sleep(3)
        print(f"SURPRISE!!!!!!!")
        time.sleep(1)
        print(f"Congrats you won the game! Did you expect that this would be the correct ending?")
        time.sleep(1)
        print(f"Thank you for playing")
        time.sleep(1)
        print(f"Returning to the start sequence in: ")
        time.sleep(1)
        print(f"3")
        time.sleep(2)
        print(f"2")
        time.sleep(2)
        print(f"1")
        time.sleep(2)
        pregame()
    else:
        print(f"....")
        time.sleep(5)
        print(f"....")
        time.sleep(5)
        print(f"\"Was that a dream???\"")
        print(f"")
        print(f"You wake up")
        time.sleep(5)
        print(f"An incoherent string of text is on your screen and your face is imprinted with the keys from your keyboard")
        time.sleep(5)
        print()
        print(f"\"Time to get back to work and do these tickets in my queue: \"")
        time.sleep(6)
        print(f"....")
        time.sleep(6)
        print(f"Just kidding! We aren't making you start all the way over! But please only select between 1 and 2 for your restaurant")
        time.sleep(3)
        firstChoice3_1()

def firstChoice3_3():
    global sysadminName
    print(f"Damn. You accept your fate and open the door to talk to your manager")
    time.sleep(5)
    print(f"Hey {sysadminName}! Did you see the Cowboys game last night? This is our year!")
    time.sleep(5)
    print(f"\"Cowboys fans.... every year is their year. I wasn't even alive the last time they won something\" you think to yourself")
    time.sleep(5 )
    print("You continue to humor your manager while covering the Giants logo on your steering wheel.")
    time.sleep(5)
    print(f"Before you know it, 30 mins have passed and you're not quite sure what subject you're on...")
    time.sleep(6)
    print(f"He eventually talks you to death..... literally....")
    time.sleep(6)
    print(f"Rewinding sequence in: ")
    time.sleep(2)
    print(f"3")
    time.sleep(2)
    print(f"2")
    time.sleep(2)
    print(f"1")
    time.sleep(2)
    firstChoice3()
    
def pregame():
    print("")
    print("")
    time.sleep(2)
    print(f"    #########################################")
    time.sleep(2)
    print(f"    Welcome to Terrible Sysadmin Simulator!")
    time.sleep(2)
    print(f"    #########################################")
    time.sleep(2)
    print()
    print()

    loop = True
    while loop is True:
        start = input(f"Start the game? y/yes/n/no: ")
        start = start.lower()
        if start == "n" or start == "no":
            print()
            print("Goodbye :(")
            print()
            break
        elif start == "y" or start == "yes":
            print()
            intro()
            loop = 2
        else:
            print()
            print(f"Please enter \"y\" or \"n\" or \"no\" or \"yes\"")
            print()

pregame()